name: "Re-trigger Workflows on open PRs"

on:
  push:
    branches:
      - main
  
jobs:
  retrigger-workflows-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: jolube/retrigger-workflows-on-open-prs@master
        with:
          github_token: ${{ secrets.gentx }}
          skip_failed_runs: false
