name: "Re-trigger Workflows on open PRs"

on:
  push:
    # Here you can limit the branches where you want this action to be run
  
jobs:
  retrigger-workflows-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: tiagobento/retrigger-workflows-on-open-prs@master
        with:
          github_token: ${{ secrets.gentx }}
